### ISSUE TITLE
A couple of issues

### ISSUE THREAD

**Issue by Sailfish** [akrayvo/riot-slider#1]
Hello akrayvo, I really like this slider. It's robust and customizable. I have a series of slides that I only want the prev/next buttons on the side of the image to control the carousel, i.e., no numbers, prev/next, play or pause buttons enabled. I've set the overrides as follows:

data-do-show-buttons="false"
data-previous-next-display="sides"
data-button-number-display="never"

While they do hide the bottom buttons, the buttons on the sides of the slides fail to work.

Also, since there a many slides (30+), I have a navigation section to the left of the display where I have links to the start of different chronological slide events, e.g., toddler, childhood, teen years, &c. While adding CSS IDs on the respective [li] images works, it appears to confuse riot-slider's ability to use the prev/next buttons to the sides of the slides. Is there a way I can use a onclick archor in the navigation links to essentially mimic what the buttons for those slides do. For example:
[a onclick="event handler" class="slide-link-number"]6[/a]
![RiotSliderExample](https://user-images.githubusercontent.com/110050/179171922-fe9df38a-c429-4203-941f-23a1a6805307.jpg)

**Comment by akrayvo** [comment]
this issue should be resolved.
sorry for the delay. also thanks for finding the bug and the detailed notes.
